const memberFormTestId = {
  NEW_BUTTON: "NEW_MEMBER_BUTTON",
  CANCEL_BUTTON: "CANCEL_MEMBER_BUTTON",
  SAVE_AND_UPDATE_BUTTON: "SAVE_AND_UPDATE_BUTTON_MEMBER_BUTTON",
  DIALOG_TITLE: "MEMBER_FORM_DIALOG_TITLE",
  DIALOG_CONTENT: "MEMBER_FORM_DIALOG_CONTENT",
  PRONOUN_FIELD: "MEMBER_FORM_PRONOUN_FIELD",
  NICKNAME_FIELD: "MEMBER_FORM_NICKNAME_FIELD",
  PRIMARY_TWITCH: "MEMBER_FORM_PRIMARY_TWITCH",
  SECONDARY_TWITCH: "MEMBER_FORM_SECONDARY_TWITCH",
  STREAM_AT_FIELD: "MEMBER_FORM_STREAM_AT_FIELD",
  SOCIALS_FIELD: "MEMBER_FORM_SOCIALS_FIELD",
};

export { memberFormTestId };
