const testId = {
  TABS_ROOT: "TABS_ROOT",
  TAB_RUN_BUTTON: "TAB_ITEM_RUN_BUTTON",
  TAB_MEMBER_BUTTON: "TAB_ITEM_MEMBER_BUTTON",
  TAB_EVENTS_BUTTON: "TAB_ITEM_EVENTS_BUTTON",
  TAB_FILES_BUTTON: "TAB_ITEM_FILES_BUTTON",
  TAB_EXTENSIONS_BUTTON: "TAB_ITEM_EXTENSIONS_BUTTON",
  TAB_ADVANCED_BUTTON: "TAB_ITEM_ADVANCED_BUTTON",
};

export { testId };
