export const eventFormTestId = {
  NEW_BUTTON: "NEW_EVENT_BUTTON",
  CANCEL_BUTTON: "CANCEL_EVENT_BUTTON",
  SAVE_AND_UPDATE_BUTTON: "SAVE_AND_UPDATE_BUTTON_EVENT_BUTTON",
  NAME_FIELD: "EVENT_FORM_NAME",
  SCHEDULE_LINK_FIELD: "EVENT_FORM_SCHEDULE_LINK",
};
